// Regenerates stops.js from the Naolib GTFS feed.
// Run when the GTFS feed is renewed (monthly): node build-stops.mjs
// Needs curl + unzip on PATH. ponytail: shelling out beats vendoring a zip reader.
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const DATASET =
  "https://data.nantesmetropole.fr/api/explore/v2.1/catalog/datasets/244400404_transports_commun_naolib_nantes_metropole_gtfs/records?limit=1";

const { results } = await (await fetch(DATASET)).json();
const { url, filename } = results[0].fichier;
console.log(`GTFS: ${filename} (valid ${results[0].debut_de_validite} → ${results[0].fin_de_validite})`);

const dir = mkdtempSync(join(tmpdir(), "naolib-"));
const zip = join(dir, "gtfs.zip");
execFileSync("curl", ["-sL", "-o", zip, url]);
execFileSync("unzip", ["-o", "-q", zip, "stops.txt", "-d", dir]);

const lines = readFileSync(join(dir, "stops.txt"), "utf8").trim().split("\n");
const cols = lines[0].split(",");
// GTFS quotes every text field but Naolib stop names contain no commas — split is safe here.
const rows = lines.slice(1).map((l) => {
  const cells = l.split(",").map((c) => c.replace(/^"|"$/g, ""));
  return Object.fromEntries(cols.map((c, i) => [c, cells[i]]));
});

const quays = new Map(); // parent stop_id -> [quay numbers]
for (const r of rows) {
  if (r.location_type !== "0") continue;
  const list = quays.get(r.parent_station) || [];
  list.push(Number(r.stop_id.split(":")[2]));
  quays.set(r.parent_station, list);
}

const stops = rows
  .filter((r) => r.location_type === "1" && quays.has(r.stop_id))
  .map((r) => [
    r.stop_name,
    Number(Number(r.stop_lat).toFixed(5)),
    Number(Number(r.stop_lon).toFixed(5)),
    quays.get(r.stop_id).sort((a, b) => a - b),
  ]);

// The network is now the only thing standing between a truncated download and
// a deployed index that silently returns no departures. 1044 stops today; a
// feed that parses to far fewer is malformed, not a real network change.
if (stops.length < 900) {
  throw new Error(`only ${stops.length} stops parsed — refusing to overwrite stops.js`);
}

writeFileSync(
  new URL("stops.js", import.meta.url),
  `// Generated by build-stops.mjs from the Naolib GTFS feed. Do not edit by hand.\n` +
    `// Each entry: [name, lat, lon, [quay ids]] — quay ids are SIRI MonitoringRefs\n` +
    `// (FR_NAOLIB:Quay:<id>). Source valid ${results[0].debut_de_validite} → ${results[0].fin_de_validite}.\n` +
    `export default ${JSON.stringify(stops)};\n`
);

console.log(`Wrote stops.js: ${stops.length} stops, ${rows.length - stops.length} quays folded in`);
